name: Release Compiled PDF
on:
  push:
    tags:
      - '*.*.*'
jobs:
  build_latex:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Run the build process with Docker
        uses: addnab/docker-run-action@v3
        with:
            image: dxjoke/tectonic-docker:latest
            options: -v ${{ github.workspace }}:/usr/src/tex/
            run: tectonic /usr/src/tex/index.tex --outdir /usr/src/tex/
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          body: PDF found in Assets
          files: ${{ github.workspace }}/index.pdf
          token: ${{ secrets.GITHUB_TOKEN }}